### ISSUE TITLE
Show Spotify http link [feature]

### ISSUE THREAD

**Issue by jcalonso** [johnelse/spotify-cli#7]
It will be great to be able to get the http link of the current song playing like:

`spotify-cli http-link`

and will output:

`http://open.spotify.com/track/[song-hash]`

Then it will be easy to share the current playing song by just doing (in os x):

`spotify-cli http-link | pbcopy`

**Comment by johnelse** [comment]
Hi, good idea!

I've actually been thinking of making the output of `now-playing` more easily machine readable, and adding more info to it, e.g.

```
$ spotify-cli now-playing
artist=foo
track=bar
http_link=baz
...
```

That way you could easily grep and cut a specific item out of the output, or even eval the whole output and add everything as variables in your environment. What do you think?

n.b. I'll have to check that the http link is actually available both via DBus and osascript.

**Comment by jcalonso** [comment]
Yeah, thats sounds great! :+1:

**Comment by johnelse** [comment]
Finally got around to doing this in https://github.com/johnelse/spotify-cli/commit/96e769d8a3639883ac41b35bd5cc3cfdfd8a220f

```
$ spotify-cli now-playing
spotify_artist_name="Devin Townsend"
spotify_track_name="Namaste"
spotify_http_url="https://open.spotify.com/track/0SGshBWnI3aDs3uuTQl7oM"
```

Hope you like it :-) an OPAM release is on the way: https://github.com/ocaml/opam-repository/pull/5042
