### ISSUE TITLE
Cannot play anything :(

### ISSUE THREAD

**Issue by OleksandrRakovets** [johnelse/spotify-cli#8]
Hello!

I've installed opam via brew and spotify-cli, but cannot get it to work.
```
$ spotify-cli play-pause
$ 22:31: execution error: The variable playpause is not defined. (-2753)

$ spotify-cli play-album "White Stripes - Elephant"
$ 22:32: syntax error: A identifier can’t go after this identifier. (-2740)
```

Also it's not clear does cli require the desktop client to be opened? When I close it the cli says
```
$ spotify-cli play-album "White Stripes - Elephant"
Spotify service not found - is it running?
```

The installed versions are: spotify-cli 0.1, opam 1.2.0, Spotify for Mac OS 1.0.1.1060.gc75ebdfd

Did I do anything wrong?

**Comment by johnelse** [comment]
Hi, and thanks for the report!

That's strange, maybe the applescript interface has changed. I'll check it out tonight as I don't have a mac handy right now.

    Also it's not clear does cli require the desktop client to be opened?

Yes, the desktop client needs to be running - the cli queries the spotify web API directly, but it relays all play/pause/etc. commands on to the desktop client.

**Comment by johnelse** [comment]
Looks like AppleScript support is broken in recent versions of Spotify - see [here](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434).

I followed the workaround suggested above and got some of the commands working again, however Spotify still seems to ignore the AppleScript command "play track" which is used by `play-album`, `play-artist` and `play-track`, so those are still broken. I'll keep investigating...

**Comment by johnelse** [comment]
Hi, I've just upgraded to Spotify.app version `1.0.5.186.ga9c24d6a` and AppleScript support seems to be fixed - could you try upgrading and let me know if this works for you?

**Comment by johnelse** [comment]
I'm going to close this now as I believe it's fixed. Please reopen if you have any issues.

**Comment by OleksandrRakovets** [comment]
Thanks John. I seem to have broken the opam thing. Will reinstall it and check the update later and let you know.
