### ISSUE TITLE
Can no longer use DBus with spotify 1.x on linux

### ISSUE THREAD

**Issue by johnelse** [johnelse/spotify-cli#9]
The spotify client seems to no longer have DBus support, which means the linux version of spotify-cli is totally broken.

An alternative may be to use the local WebHelper API:

http://cgbystrom.com/articles/deconstructing-spotifys-builtin-http-server/
https://www.npmjs.com/package/node-spotify-webhelper
https://github.com/cgbystrom/spotify-local-http-api

This seems to be a cross-platform API, so may remove the need for the linux and OSX versions of spotify-cli to have different backends.

**Comment by simonjbeaumont** [comment]
:cry:

**Comment by johnelse** [comment]
It [looks like this was unintentional](https://community.spotify.com/t5/Spotify-Announcements/Spotify-Client-1-x-beta-for-Linux-has-been-released/m-p/1147714#M7279) so hopefully DBus will be back in a future version...

**Comment by simonjbeaumont** [comment]
Working now in Spotify `1.0.13.112.g539ef41b` on Linux:
```
[sjbx@kif ~] spotify --version
spotify: /lib64/libcurl.so.4: no version information available (required by spotify)
Spotify version 1.0.13.112.g539ef41b, Copyright (c) 2015, Spotify Ltd
```

**Comment by johnelse** [comment]
Yep, working for me too.
